project:
  type: website
  output-dir: docs
  title: "Vandalizer Wiki"

website:
  title: "Vandalizer Wiki"
  page-navigation: true
  repo-url: https://github.com/nate-layman/vandalizer-manual
  repo-actions: [edit]
  sidebar:
    style: "floating"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Disclaimer"
        href: disclaimer.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Interface"
        href: interface.qmd
      - text: "Tasks"
        href: tasks.qmd
      - text: "Workflows"
        href: workflows.qmd
      - text: "Examples"
        href: example.qmd
      - text: "Next Steps"
        href: next-steps.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: left
    number-sections: false
