[workspace]
authors = ["Nathan Layman <nlayman@uidaho.edu>"]
channels = ["conda-forge"]
name = "vandalizer-manual"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
quarto = "quarto"

[dependencies]
yaml = ">=0.2.5,<0.3"
jupyter = ">=1.1.1,<2"
pandas = ">=2.3.0,<3"
plotly = ">=6.2.0,<7"
quarto = ">=1.7.32,<2"
