name: Pre-Deploy Tasks
on:
  push:
    branches: [ main ] # adjust branch name if needed

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Document
        run: quarto render
