# .github/workflows/update-dashboard.yml
name: Update Roadmap
on:
  schedule:
    # Run daily at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Document (first pass)
        run: quarto render
        
      - name: Collect Issues Data
        run: |
          mkdir -p docs/data
          repo="ui-insight/vandalizer"
          
          if ! gh auth status; then
            exit 1
          fi
          
          if all_issues=$(gh api "repos/$repo/issues" \
            --paginate \
            --jq '.[] | select(.pull_request == null) | {
              id: .id,
              number: .number,
              title: .title,
              url: .html_url,
              state: .state,
              created_at: .created_at,
              updated_at: .updated_at,
              labels: [.labels[].name],
              assignees: [.assignees[].login],
              repository: "'$repo'"
            }'); then
            echo "$all_issues" | jq '.' > docs/data/issues.json
          else
            echo "[]" > docs/data/issues.json
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.VANDALIZER_ISSUES_TOKEN }}
          
      - name: Final Quarto Render
        run: quarto render
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          
          if git diff --staged --quiet; then
            exit 0
          else
            git commit -m "Update roadmap dashboard - $(date)"
            git push
          fi
