name: Update Roadmap
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Collect Issues Data
        run: |
          mkdir -p data
          repo="ui-insight/vandalizer"
          echo "Fetching issues from $repo..."
          
          all_issues=$(gh api "repos/$repo/issues" \
            --paginate \
            --jq '.[] | select(.pull_request == null) | {
              id: .id,
              number: .number,
              title: .title,
              url: .html_url,
              state: .state,
              created_at: .created_at,
              updated_at: .updated_at,
              labels: [.labels[].name],
              assignees: [.assignees[].login],
              repository: "'$repo'"
            }')
          
          echo "$all_issues" | jq '.' > data/issues.json
          issue_count=$(echo "$all_issues" | jq 'length')
          echo "Collected $issue_count issues from $repo"
        env:
          GH_TOKEN: ${{ github.token }}  # or your PAT if needed
          
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Quarto Document
        run: quarto render
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update roadmap dashboard - $(date)"
            git push
            echo "Changes pushed - this will trigger the pages-build-deployment workflow"
          fi
        
